title: Tibix's Blog
author: TibixDev
email: fuloptibi03@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog serves the purpose of documenting my programming
  adventures and other things I do.

# social links
twitter_username: ItzTibix
github_username:  TibixDev

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
